import type { Metadata } from 'next'
import '../../styles/global.scss'
import Script from "next/script";
import React from "react";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=ADLaM+Display&family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet" />
        <body>{children}</body>
        </html>
    )
}
